;
; File generated by cc65 v 2.18 - Git dbba5f3
;
	.fopt		compiler,"cc65 v 2.18 - Git dbba5f3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_acia_putc
	.import		_lcd_putc
	.export		_udp_wr_reg
	.export		_vdp_wr_reg

; ---------------------------------------------------------------
; void __near__ udp_wr_reg (char red, char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_udp_wr_reg: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _lcd_putc
	ldy     #$00
	lda     (sp),y
	jsr     _acia_putc
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ vdp_wr_reg (char red, char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_vdp_wr_reg: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _lcd_putc
	ldy     #$00
	lda     (sp),y
	jsr     _acia_putc
	jmp     incsp2

.endproc

